// Subject → { icon, img, credit } used as card art wherever the R2 curriculum
// library is browsed by subject (Student Resources, Facilitator Resources).
// Shared across portals so both stay visually consistent and don't drift.
// Images are real photos from Wikimedia Commons (public domain / CC-licensed) —
// credit is shown on each card since several licenses (CC BY, CC BY-SA) require it.
// Paths are relative to a page under frontend/<Portal>/, e.g. ../Assets/subjects/...
const SUBJECT_THEME = {
    "Agriculture": { icon: "🌾", img: "../Assets/subjects/agriculture.jpg", credit: "Fredericknoronha / Wikimedia Commons (CC BY-SA 4.0)" },
    "Auditing": { icon: "📋", img: "../Assets/subjects/auditing.jpg", credit: "HABS / Wikimedia Commons (Public domain)" },
    "Biology": { icon: "🧬", img: "../Assets/subjects/biology.jpg", credit: "Scott L. Gardner / Wikimedia Commons (CC BY-SA 4.0)" },
    "Chemistry": { icon: "⚗️", img: "../Assets/subjects/chemistry.jpg", credit: "Belikov Maxim / Wikimedia Commons (CC BY 4.0)" },
    "Clinical Placement": { icon: "🏥", img: "../Assets/subjects/clinical-placement.jpg", credit: "U.S. Navy / Wikimedia Commons (Public domain)" },
    "Computer Science": { icon: "💻", img: "../Assets/subjects/computer-science.jpg", credit: "Crew crew / Wikimedia Commons (CC0)" },
    "Creative Arts Music and Fine Arts": { icon: "🎨", img: "../Assets/subjects/creative-arts-music-and-fine-arts.jpg", credit: "Bartolomeo Bettera / Wikimedia Commons (Public domain)" },
    "Creative Performance": { icon: "🎭", img: "../Assets/subjects/creative-performance.jpg", credit: "Arquivo histórico de Sarria / Wikimedia Commons (CC BY-SA 3.0)" },
    "Economics": { icon: "📈", img: "../Assets/subjects/economics.png", credit: "Nikolay Zvezdin / Wikimedia Commons (CC BY-SA 4.0)" },
    "English": { icon: "📖", img: "../Assets/subjects/english.jpg", credit: "Micheal Kaluba / Wikimedia Commons (CC BY-SA 4.0)" },
    "Entrepreneurship": { icon: "💡", img: "../Assets/subjects/entrepreneurship.jpg", credit: "Wikimedia Commons (CC0)" },
    "Ethics": { icon: "⚖️", img: "../Assets/subjects/ethics.jpg", credit: "Domenico Fetti / Wikimedia Commons (Public domain)" },
    "Financial Accounting": { icon: "💰", img: "../Assets/subjects/financial-accounting.jpg", credit: "Ken Lund / Wikimedia Commons (CC BY-SA 2.0)" },
    "Foundations of Education": { icon: "🎓", img: "../Assets/subjects/foundations-of-education.jpg", credit: "Harrison Keely / Wikimedia Commons (CC BY 4.0)" },
    "French": { icon: "🇫🇷", img: "../Assets/subjects/french.jpg", credit: "Getfunky Paris / Wikimedia Commons (CC BY 2.0)" },
    "Fundamentals of Nursing": { icon: "💉", img: "../Assets/subjects/clinical-placement.jpg", credit: "U.S. Navy / Wikimedia Commons (Public domain)" },
    "General Studies": { icon: "🧭", img: "../Assets/subjects/general-studies.jpg", credit: "Gary Todd / Wikimedia Commons (CC0)" },
    "Geography": { icon: "🌍", img: "../Assets/subjects/geography.jpg", credit: "Auguste Henri Dufour / Wikimedia Commons (Public domain)" },
    "History": { icon: "🏛️", img: "../Assets/subjects/history.jpg", credit: "Gary Todd / Wikimedia Commons (CC0)" },
    "History & Citizenship": { icon: "🏛️", img: "../Assets/subjects/history-citizenship.jpg", credit: "JJ Harrison / Wikimedia Commons (CC BY-SA 3.0)" },
    "Home Science": { icon: "🏠", img: "../Assets/subjects/home-science.jpg", credit: "Shixart1985 / Wikimedia Commons (CC BY 2.0)" },
    "ICT": { icon: "💻", img: "../Assets/subjects/ict.jpg", credit: "Bill Branson / Wikimedia Commons (Public domain)" },
    "ICT in Accounting": { icon: "🖥️", img: "../Assets/subjects/ict-in-accounting.jpg", credit: "Wikimedia Commons (CC0)" },
    "Integrated Science": { icon: "🔬", img: "../Assets/subjects/integrated-science.jpg", credit: "U.S. Department of Energy / Wikimedia Commons (Public domain)" },
    "Kinyarwanda": { icon: "🗣️", img: "../Assets/subjects/kinyarwanda.jpg", credit: "Ericnkurunziza / Wikimedia Commons (CC BY-SA 4.0)" },
    "Kiswahili": { icon: "🗣️", img: "../Assets/subjects/kiswahili.jpg", credit: "NASA Earth Observatory / Wikimedia Commons (Public domain)" },
    "Literature in English": { icon: "📚", img: "../Assets/subjects/literature-in-english.jpg", credit: "Wikimedia Commons (CC0)" },
    "Management Accounting": { icon: "📊", img: "../Assets/subjects/management-accounting.jpg", credit: "Traceries / Wikimedia Commons (Public domain)" },
    "Mathematics": { icon: "➗", img: "../Assets/subjects/mathematics.jpg", credit: "Manuelzapata04 / Wikimedia Commons (CC BY-SA 4.0)" },
    "Mathematics for Accounting": { icon: "🧮", img: "../Assets/subjects/mathematics-for-accounting.jpg", credit: "Coyau / Wikimedia Commons (CC BY-SA 3.0)" },
    "Medical Pathology": { icon: "🩺", img: "../Assets/subjects/medical-pathology.jpg", credit: "CDC / Wikimedia Commons (Public domain)" },
    "Music": { icon: "🎵", img: "../Assets/subjects/music.jpg", credit: "Maurizio Pesce / Wikimedia Commons (CC BY 2.0)" },
    "Physical Education": { icon: "⚽", img: "../Assets/subjects/physical-education.jpg", credit: "ThoroughlyReviewed / Wikimedia Commons (CC BY 2.0)" },
    "Physics": { icon: "⚛️", img: "../Assets/subjects/physics.jpg", credit: "Stanislav Liubauskas / Wikimedia Commons (CC BY 4.0)" },
    "Religion & Ethics": { icon: "🕊️", img: "../Assets/subjects/religion-ethics.jpg", credit: "Dragfyre / Wikimedia Commons (CC BY-SA 3.0)" },
    "Religious Studies": { icon: "🕊️", img: "../Assets/subjects/religion-ethics.jpg", credit: "Dragfyre / Wikimedia Commons (CC BY-SA 3.0)" },
    "Science and Elementary Technology": { icon: "🔧", img: "../Assets/subjects/science-and-elementary-technology.jpg", credit: "Wikimedia Commons (Public domain)" },
    "Social Studies": { icon: "🏘️", img: "../Assets/subjects/social-studies.jpg", credit: "Bembety / Wikimedia Commons (CC BY-SA 4.0)" },
    "Social and Religious Studies": { icon: "🏘️", img: "../Assets/subjects/religion-ethics.jpg", credit: "Dragfyre / Wikimedia Commons (CC BY-SA 3.0)" },
    "Special Education Needs": { icon: "🤝", img: "../Assets/subjects/special-education-needs.jpg", credit: "DFAT / Wikimedia Commons (CC BY 4.0)" },
    "Taxation": { icon: "🧾", img: "../Assets/subjects/taxation.jpg", credit: "Blogtrepreneur / Wikimedia Commons (CC BY 2.0)" },
};
const DEFAULT_SUBJECT_THEME = { icon: "📘", img: "", credit: "" };
